In [1]:
import pandas as pd
import numpy as np

In [6]:
df1 = pd.read_csv("./서울시 상권분석서비스(영역-상권).csv", encoding='cp949')
df1

,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,엑스좌표_값,와이좌표_값,자치구_코드,자치구_코드_명,행정동_코드,행정동_코드_명,영역_면적
0,A,골목상권,3110008,배화여자대학교(박노수미술관),197093,453418,11110,종로구,11110515,청운효자동,149264
1,A,골목상권,3110009,자하문터널,196991,455057,11110,종로구,11110550,부암동,178306
2,A,골목상권,3110010,평창동서측,197064,456643,11110,종로구,11110560,평창동,369415
3,A,골목상권,3110017,정독도서관,198581,453781,11110,종로구,11110600,가회동,83855
4,A,골목상권,3110018,중앙고등학교,198883,453690,11110,종로구,11110600,가회동,166872
...,...,...,...,...,...,...,...,...,...,...,...
1645,U,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,198397,451614,11140,중구,11140520,소공동,983618
1646,U,관광특구,3001493,동대문패션타운 관광특구,200996,451976,11140,중구,11140590,광희동,606058
1647,U,관광특구,3001494,종로?청계 관광특구,199796,452274,11110,종로구,11110615,종로1?2?3?4가동,653127
1648,U,관광특구,3001495,잠실 관광특구,210188,446334,11710,송파구,11710562,방이2동,2462734
1649,U,관광특구,3001496,강남 마이스 관광특구,205282,445736,11680,강남구,11680580,삼성1동,237892

In [7]:
df2 = pd.read_csv("./서울시 상권분석서비스(점포-상권).csv", encoding="cp949")
df2

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,20252,R,전통시장,3130327,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",CS300043,전자상거래업,4,4,0,0,0,0,0
1,20252,R,전통시장,3130327,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",CS300035,인테리어,2,2,0,0,0,0,0
2,20252,R,전통시장,3130327,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",CS300029,애완동물,1,1,0,0,0,0,0
3,20252,R,전통시장,3130327,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",CS300027,섬유제품,2,2,0,0,0,0,0
4,20252,R,전통시장,3130327,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",CS300024,운동/경기용품,5,5,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459505,20241,U,관광특구,3001491,이태원 관광특구,CS100005,제과점,25,30,0,0,0,0,5
459506,20241,U,관광특구,3001491,이태원 관광특구,CS100004,양식음식점,221,226,2,5,2,5,5
459507,20241,U,관광특구,3001491,이태원 관광특구,CS100003,일식음식점,24,25,0,0,0,0,1
459508,20241,U,관광특구,3001491,이태원 관광특구,CS100002,중식음식점,17,19,0,0,0,0,2
459509,20241,U,관광특구,3001491,이태원 관광특구,CS100001,한식음식점,122,134,8,10,3,4,12

In [10]:
df1.columns

Index(['상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '엑스좌표_값', '와이좌표_값',
       '자치구_코드', '자치구_코드_명', '행정동_코드', '행정동_코드_명', '영역_면적'],
      dtype='object')

In [11]:
df2.columns

Index(['기준_년분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '서비스_업종_코드',
       '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률',
       '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')

In [2]:
df_road_population = pd.read_csv("./서울시 상권분석서비스(길단위인구-상권).csv", encoding='cp949')
df_road_population

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
0,20252,U,관광특구,3001496,강남 마이스 관광특구,106928,52435,54493,7088,21778,...,27043,21393,5266,15044,15308,17475,18170,17152,13095,10684
1,20252,U,관광특구,3001495,잠실 관광특구,4116967,1951388,2165578,407384,949932,...,658382,900623,483598,565714,570891,574479,589440,616438,619744,580259
2,20252,U,관광특구,3001494,종로?청계 관광특구,8537311,4476428,4060884,322168,1533817,...,1786024,1686973,684131,1318020,1311528,1399371,1376796,1329573,1005568,796454
3,20252,U,관광특구,3001493,동대문패션타운 관광특구,3489708,1624950,1864757,196001,649607,...,551648,660777,416430,536087,541289,557366,555502,516952,392095,390417
4,20252,U,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,6952851,3278243,3674608,287579,1200664,...,1702240,1300602,344642,1096780,1095901,1183241,1155247,1105066,721777,594838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42883,20191,A,골목상권,3110005,세검정,129171,55368,73803,19624,15305,...,13667,21367,20706,18686,18746,18727,18736,18576,17782,17918
42884,20191,A,골목상권,3110004,대신고등학교,495628,226246,269381,94335,57494,...,70258,94736,65414,69892,70158,71562,71577,70647,70556,71236
42885,20191,A,골목상권,3110003,세검정초등학교,706686,310470,396215,128431,82037,...,74478,96768,85012,100783,100429,100067,99815,98912,102760,103921
42886,20191,A,골목상권,3110002,독립문역 1번,540585,246868,293717,96885,65609,...,75590,96631,70361,76301,77283,79044,78826,78583,75041,75508
42887,20191,A,골목상권,3110001,이북5도청사,155680,68432,87248,27743,15216,...,17671,22780,19199,21722,21682,21627,21636,21604,23276,24132

In [3]:
df_road_population.loc[df_road_population['상권_코드_명'] == '강남 마이스 관광특구']

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
0,20252,U,관광특구,3001496,강남 마이스 관광특구,106928,52435,54493,7088,21778,...,27043,21393,5266,15044,15308,17475,18170,17152,13095,10684
1649,20251,U,관광특구,3001496,강남 마이스 관광특구,100649,49922,50727,7069,20015,...,25342,20967,5110,14344,15196,15603,16864,16517,11758,10364
3299,20244,U,관광특구,3001496,강남 마이스 관광특구,105501,51291,54210,8292,21082,...,26401,22128,5374,15171,15776,16688,17391,17045,12783,10645
4948,20243,U,관광특구,3001496,강남 마이스 관광특구,108678,52145,56533,9633,22198,...,27529,22375,5443,15107,15971,16900,17793,17480,13833,11595
6596,20242,U,관광특구,3001496,강남 마이스 관광특구,106718,52725,53993,7813,21351,...,26480,21795,5590,15034,16820,16036,17470,17305,12806,11249
8245,20241,U,관광특구,3001496,강남 마이스 관광특구,109292,54238,55054,7982,21853,...,27041,22995,6011,15002,16018,17973,17774,17305,13328,11892
9894,20234,U,관광특구,3001496,강남 마이스 관광특구,113583,55514,58069,8833,22861,...,28141,24240,6152,15176,16745,18117,18747,18309,14392,12097
11542,20233,U,관광특구,3001496,강남 마이스 관광특구,116820,56546,60274,9741,24430,...,28982,24541,6292,16713,17686,18378,18560,18293,14662,12527
13191,20232,U,관광특구,3001496,강남 마이스 관광특구,111108,55410,55701,8166,22991,...,27393,23286,6089,14719,16219,17924,18904,18166,13814,11365
14840,20231,U,관광특구,3001496,강남 마이스 관광특구,109623,55025,54598,8151,22623,...,27154,23482,6106,15714,16427,17070,18252,17618,13137,11402
16489,20224,U,관광특구,3001496,강남 마이스 관광특구,113561,56267,57295,8423,23526,...,27583,24323,6411,15349,17220,18047,18597,18288,13967,12091
18138,20223,U,관광특구,3001496,강남 마이스 관광특구,113638,55753,57883,9279,24236,...,27947,24322,6551,15725,16780,17683,18492,17894,14370,12695
19788,20222,U,관광특구,3001496,강남 마이스 관광특구,107600,53897,53703,7472,22427,...,25869,22814,6334,15053,16396,17021,17690,17337,13132,10973
21438,20221,U,관광특구,3001496,강남 마이스 관광특구,93390,46991,46400,6299,19804,...,22411,20142,5276,13678,13771,14115,15319,15170,11452,9885
23088,20214,U,관광특구,3001496,강남 마이스 관광특구,103205,51392,51813,6654,22140,...,24843,22387,5867,14060,15319,16347,16803,16489,13125,11062
24738,20213,U,관광특구,3001496,강남 마이스 관광특구,84855,43095,41760,5314,18049,...,19919,17399,4774,12505,13086,13254,14078,13797,9751,8383
26388,20212,U,관광특구,3001496,강남 마이스 관광특구,96464,48133,48331,5217,20796,...,22935,20453,5426,14566,15122,14893,15649,15447,11288,9499
28038,20211,U,관광특구,3001496,강남 마이스 관광특구,88339,44323,44016,5007,18867,...,21156,18978,4777,13462,14131,14253,14044,13336,10262,8853
29688,20204,U,관광특구,3001496,강남 마이스 관광특구,91269,46431,44838,4355,20016,...,21537,19590,5208,14191,14794,15118,14569,13991,10208,8398
31338,20203,U,관광특구,3001496,강남 마이스 관광특구,98252,49499,48753,5586,22390,...,23094,21268,5892,14748,15687,15342,16204,16083,11101,9087
32988,20202,U,관광특구,3001496,강남 마이스 관광특구,90613,45927,44687,4603,20342,...,21507,19724,5140,14430,14538,14658,14711,14524,9669,8086
34638,20201,U,관광특구,3001496,강남 마이스 관광특구,97891,49221,48669,5979,22591,...,23585,21981,5853,15132,15918,15510,15854,15430,10676,9371
36288,20194,U,관광특구,3001496,강남 마이스 관광특구,131358,62639,68719,10374,31615,...,32865,30606,8084,18090,19589,19753,20612,21333,17423,14558
37938,20193,U,관광특구,3001496,강남 마이스 관광특구,125819,59425,66394,10486,29946,...,31058,28322,7789,17651,18512,19123,19696,19839,16395,14600
39588,20192,U,관광특구,3001496,강남 마이스 관광특구,119257,57468,61789,8332,29377,...,29312,26827,7329,16172,17282,18090,19140,19567,15600,13407
41238,20191,U,관광특구,3001496,강남 마이스 관광특구,115445,55904,59539,8107,27752,...,28548,26902,7296,15993,16305,17491,18977,18810,14966,12904

In [5]:
df_max = df_road_population[df_road_population['기준_년분기_코드'] == df_road_population['기준_년분기_코드'].max()]
df_max

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
0,20252,U,관광특구,3001496,강남 마이스 관광특구,106928,52435,54493,7088,21778,...,27043,21393,5266,15044,15308,17475,18170,17152,13095,10684
1,20252,U,관광특구,3001495,잠실 관광특구,4116967,1951388,2165578,407384,949932,...,658382,900623,483598,565714,570891,574479,589440,616438,619744,580259
2,20252,U,관광특구,3001494,종로?청계 관광특구,8537311,4476428,4060884,322168,1533817,...,1786024,1686973,684131,1318020,1311528,1399371,1376796,1329573,1005568,796454
3,20252,U,관광특구,3001493,동대문패션타운 관광특구,3489708,1624950,1864757,196001,649607,...,551648,660777,416430,536087,541289,557366,555502,516952,392095,390417
4,20252,U,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,6952851,3278243,3674608,287579,1200664,...,1702240,1300602,344642,1096780,1095901,1183241,1155247,1105066,721777,594838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1644,20252,A,골목상권,3110005,세검정,88410,38891,49519,15890,8402,...,9892,14643,12518,12574,12713,12653,12466,12581,12587,12836
1645,20252,A,골목상권,3110004,대신고등학교,664277,305472,358806,131060,77303,...,91584,124585,81521,94849,96048,95417,95267,94923,94299,93476
1646,20252,A,골목상권,3110003,세검정초등학교,320076,145679,174397,76627,34918,...,34836,52335,45646,45857,46332,45482,45647,45948,45532,45278
1647,20252,A,골목상권,3110002,독립문역 1번,529414,232298,297117,94283,62166,...,69151,94830,69089,73869,75535,77550,75133,75280,77074,74974
1648,20252,A,골목상권,3110001,이북5도청사,171658,74442,97217,35182,18892,...,18662,26785,22032,23819,24034,23498,23880,24020,25787,26621

In [6]:
df_max.loc[df_max['상권_코드_명'] == '강남 마이스 관광특구']

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
0,20252,U,관광특구,3001496,강남 마이스 관광특구,106928,52435,54493,7088,21778,...,27043,21393,5266,15044,15308,17475,18170,17152,13095,10684

In [8]:
df_store = pd.read_csv('./서울시 상권분석서비스(점포-상권).csv', encoding='cp949')

In [16]:
cond_latest_store = df_store['기준_년분기_코드'] == df_store['기준_년분기_코드'].max()
cond_area_store   = df_store['상권_코드_명'] == '강남 마이스 관광특구'
selected_store = df_store[cond_latest_store & cond_area_store]
total_store = selected_store['점포_수'].sum()

In [17]:
selected_store

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
75718,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300043,전자상거래업,5,5,0,0,0,0,0
75719,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300041,예술품,10,10,0,0,0,0,0
75720,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300038,자동차부품,2,2,0,0,0,0,0
75721,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300037,중고차판매,0,0,0,0,0,1,0
75722,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300036,조명용품,25,25,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75782,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100005,제과점,19,24,0,0,0,0,5
75783,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100004,양식음식점,31,38,3,1,0,0,7
75784,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100003,일식음식점,18,24,0,0,0,0,6
75785,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100002,중식음식점,11,15,0,0,0,0,4
75786,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100001,한식음식점,47,60,0,0,2,1,13

In [18]:
total_store

np.int64(1033)

In [21]:
df_sales = pd.read_csv('./서울시 상권분석서비스(추정매출-상권).csv', encoding='cp949')

In [23]:
cond_latest_sales = df_sales['기준_년분기_코드'] == df_sales['기준_년분기_코드'].max()
cond_area_sales   = df_sales['상권_코드_명'] == '강남 마이스 관광특구'
selected_sales = df_sales[cond_latest_sales & cond_area_sales]
selected_sales

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_금액,...,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수
130028,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100001,한식음식점,3336108533,155539,2276084619,...,28756,318,49702,92254,346,23985,45866,35361,24930,11467
130029,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100002,중식음식점,9542911514,210450,6276221813,...,84535,7996,69248,113756,2212,46046,59175,34488,27355,13725
130030,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100003,일식음식점,785665338,8888,618547278,...,3410,201,3128,3448,51,1666,2624,1144,711,383
130031,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100004,양식음식점,5548939050,92980,3686832942,...,31496,3628,28789,44052,445,12607,26362,17242,10697,5489
130032,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100005,제과점,2208211103,128382,1583023170,...,39633,2882,43038,64238,803,19372,33579,25533,17343,10645
130033,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100006,패스트푸드점,2385194530,209805,1662541776,...,58979,6601,99930,88714,2657,41322,64568,41173,24858,14070
130034,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100008,분식전문점,1513608621,152618,1024733450,...,49753,7266,58993,81195,2477,31219,43999,34102,18159,10231
130035,20252,U,관광특구,3001496,강남 마이스 관광특구,CS100010,커피-음료,4562450475,410743,3202110035,...,72936,3793,147238,207822,2360,71407,132948,84406,41890,22047
130036,20252,U,관광특구,3001496,강남 마이스 관광특구,CS200006,일반의원,1300641265,15185,1227909036,...,1533,0,7637,7548,23,1300,4510,4106,2762,2484
130037,20252,U,관광특구,3001496,강남 마이스 관광특구,CS200028,미용실,816547044,7472,570666211,...,2382,321,4005,3261,14,377,1519,1877,1975,1502
130038,20252,U,관광특구,3001496,강남 마이스 관광특구,CS200030,피부관리실,460076630,1389,283613994,...,588,229,371,362,0,48,228,229,115,115
130039,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300001,슈퍼마켓,2132908356,331167,1753297514,...,67198,26861,173697,111627,2006,48479,104463,64061,48065,18250
130040,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300002,편의점,5574074102,396537,3963804424,...,118674,18283,152861,223623,3917,91206,131301,75586,49946,24531
130041,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300003,컴퓨터및주변장치판매,204433809,190,204433809,...,0,0,0,63,0,63,0,0,0,0
130042,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300004,핸드폰,565591520,7137,530630148,...,2091,0,2740,2235,72,936,1081,1153,865,865
130043,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300010,반찬가게,1738000000,55130,1098887968,...,9658,0,19032,36098,199,20684,26155,4502,2707,883
130044,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300011,일반의류,19988878385,147373,13385791472,...,55722,7055,37687,108513,980,20631,45103,36465,24113,18906
130045,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300014,신발,85064635,351,54940187,...,125,0,291,60,0,72,141,84,42,12
130046,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300015,가방,12098466206,407579,7708771752,...,158402,17584,110535,288910,2950,72106,112293,91735,66041,54321
130047,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300016,안경,1075203167,13980,645712340,...,5438,490,2324,11526,246,5338,4020,2069,1619,557
130048,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300017,시계및귀금속,2242560618,1266,1400236169,...,30,0,224,893,15,0,283,60,328,432
130049,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300018,의약품,3414303567,225725,2716758748,...,50200,128,104647,113887,1099,35068,68575,48840,36719,28234
130050,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300021,문구,1447609207,101136,1115155199,...,32043,1831,29958,56661,933,21781,28607,17925,10713,6660
130051,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300022,화장품,1312402233,30283,941217140,...,11452,2094,10015,18190,270,6348,8558,5969,4332,2731
130052,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300024,운동/경기용품,521299279,2288,291376630,...,763,106,850,1438,0,371,740,524,413,240
130053,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300026,완구,1650016925,35797,998115625,...,13778,903,13107,22690,690,12944,12959,6210,2157,837
130054,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300028,화초,962106182,30644,785962426,...,10531,296,8500,19679,407,8097,9918,5470,2895,1391
130055,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300031,가구,2970090430,1515,1530334954,...,317,0,739,776,0,0,70,317,387,741
130056,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300032,가전제품,241494948,260,0,...,0,0,130,130,0,0,0,0,0,260
130057,20252,U,관광특구,3001496,강남 마이스 관광특구,CS300036,조명용품,242309,242,242309,...,0,0,0,242,0,0,242,0,0,0

In [25]:
total_sales= selected_sales['당월_매출_금액'].sum()

In [26]:
df_resident_population = pd.read_csv('./서울시 상권분석서비스(상주인구-상권).csv', encoding='cp949')
df_worker_population = pd.read_csv('./서울시 상권분석서비스(직장인구-상권).csv', encoding='cp949')

In [2]:
df_resident_population = pd.read_csv('./서울시 상권분석서비스(상주인구-상권).csv', encoding='cp949')
df_worker_population = pd.read_csv('./서울시 상권분석서비스(직장인구-상권).csv', encoding='cp949')

In [3]:
df_resident_population.head()

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_상주인구_수,남성_상주인구_수,여성_상주인구_수,연령대_10_상주인구_수,연령대_20_상주인구_수,...,남성연령대_60_이상_상주인구_수,여성연령대_10_상주인구_수,여성연령대_20_상주인구_수,여성연령대_30_상주인구_수,여성연령대_40_상주인구_수,여성연령대_50_상주인구_수,여성연령대_60_이상_상주인구_수,총_가구_수,아파트_가구_수,비_아파트_가구_수
0,20241,R,전통시장,3130193,신수시장,59,27,32,5,6,...,7,2,3,7,5,4,11,38,0,38
1,20251,R,전통시장,3130289,봉일시장,1,1,0,0,0,...,1,0,0,0,0,0,0,1,0,1
2,20194,R,전통시장,3130304,신사상가,2,1,1,0,0,...,0,0,0,1,0,0,0,2,0,2
3,20241,R,전통시장,3130250,삼구시장(로타리상가),4,2,2,0,0,...,2,0,0,0,0,0,2,4,0,4
4,20241,A,골목상권,3110527,홍제역 2번,4722,2191,2531,690,585,...,480,345,314,428,367,396,681,2109,0,2109

In [11]:
df_resident_population[df_resident_population['상권_코드_명'] == '강남 마이스 관광특구']

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_상주인구_수,남성_상주인구_수,여성_상주인구_수,연령대_10_상주인구_수,연령대_20_상주인구_수,...,남성연령대_60_이상_상주인구_수,여성연령대_10_상주인구_수,여성연령대_20_상주인구_수,여성연령대_30_상주인구_수,여성연령대_40_상주인구_수,여성연령대_50_상주인구_수,여성연령대_60_이상_상주인구_수,총_가구_수,아파트_가구_수,비_아파트_가구_수
847,20252,U,관광특구,3001496,강남 마이스 관광특구,34,24,10,1,1,...,10,0,0,1,2,2,5,25,0,25
1991,20241,U,관광특구,3001496,강남 마이스 관광특구,34,24,10,1,1,...,10,0,0,1,2,2,5,25,0,25
3783,20242,U,관광특구,3001496,강남 마이스 관광특구,34,24,10,1,1,...,10,0,0,1,2,2,5,25,0,25
5227,20243,U,관광특구,3001496,강남 마이스 관광특구,34,24,10,1,1,...,10,0,0,1,2,2,5,25,0,25
6912,20251,U,관광특구,3001496,강남 마이스 관광특구,34,24,10,1,1,...,10,0,0,1,2,2,5,25,0,25
8541,20244,U,관광특구,3001496,강남 마이스 관광특구,34,24,10,1,1,...,10,0,0,1,2,2,5,25,0,25
11446,20194,U,관광특구,3001496,강남 마이스 관광특구,24,16,8,6,2,...,4,2,1,1,2,0,2,13,0,13
11892,20201,U,관광특구,3001496,강남 마이스 관광특구,24,16,8,6,2,...,4,2,1,1,2,0,2,13,0,13
13590,20223,U,관광특구,3001496,강남 마이스 관광특구,29,16,13,2,4,...,6,2,2,1,2,4,2,18,0,18
17180,20202,U,관광특구,3001496,강남 마이스 관광특구,24,16,8,6,2,...,4,2,1,1,2,0,2,13,0,13
18386,20224,U,관광특구,3001496,강남 마이스 관광특구,19,11,8,6,0,...,5,3,0,1,2,0,2,18,0,18
20373,20203,U,관광특구,3001496,강남 마이스 관광특구,24,16,8,6,2,...,4,2,1,1,2,0,2,13,0,13
21568,20204,U,관광특구,3001496,강남 마이스 관광특구,29,16,13,2,4,...,6,2,2,1,2,4,2,18,0,18
23175,20211,U,관광특구,3001496,강남 마이스 관광특구,29,16,13,2,4,...,6,2,2,1,2,4,2,18,0,18
24749,20212,U,관광특구,3001496,강남 마이스 관광특구,29,16,13,2,4,...,6,2,2,1,2,4,2,18,0,18
26736,20213,U,관광특구,3001496,강남 마이스 관광특구,29,16,13,2,4,...,6,2,2,1,2,4,2,18,0,18
27929,20214,U,관광특구,3001496,강남 마이스 관광특구,29,16,13,2,4,...,6,2,2,1,2,4,2,18,0,18
29918,20221,U,관광특구,3001496,강남 마이스 관광특구,29,16,13,2,4,...,6,2,2,1,2,4,2,18,0,18
31529,20233,U,관광특구,3001496,강남 마이스 관광특구,19,11,8,6,0,...,5,3,0,1,2,0,2,18,0,18
32779,20222,U,관광특구,3001496,강남 마이스 관광특구,29,16,13,2,4,...,6,2,2,1,2,4,2,18,0,18
33807,20234,U,관광특구,3001496,강남 마이스 관광특구,34,24,10,1,1,...,10,0,0,1,2,2,5,25,0,25
35083,20232,U,관광특구,3001496,강남 마이스 관광특구,19,11,8,6,0,...,5,3,0,1,2,0,2,18,0,18
36104,20231,U,관광특구,3001496,강남 마이스 관광특구,19,11,8,6,0,...,5,3,0,1,2,0,2,18,0,18

In [12]:
df_worker_population

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_직장_인구_수,남성_직장_인구_수,여성_직장_인구_수,연령대_10_직장_인구_수,연령대_20_직장_인구_수,...,남성연령대_30_직장_인구_수,남성연령대_40_직장_인구_수,남성연령대_50_직장_인구_수,남성연령대_60_이상_직장_인구_수,여성연령대_10_직장_인구_수,여성연령대_20_직장_인구_수,여성연령대_30_직장_인구_수,여성연령대_40_직장_인구_수,여성연령대_50_직장_인구_수,여성연령대_60_이상_직장_인구_수
0,20252,R,전통시장,3130019,동대문상가D동,7,3,4,0,0,...,0,1,1,1,0,0,1,2,1,0
1,20252,A,골목상권,3110005,세검정,544,306,238,0,91,...,90,85,64,30,0,54,71,64,40,9
2,20252,A,골목상권,3110023,서울대병원,87,48,39,0,12,...,11,14,12,8,0,9,11,9,7,3
3,20252,D,발달상권,3120004,종로구청,5275,2909,2366,72,1068,...,808,849,583,172,41,602,802,598,243,80
4,20252,R,전통시장,3130018,동대문문구완구거리(동대문문구완구시장),318,142,176,0,0,...,10,40,44,48,0,0,44,72,50,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42553,20243,D,발달상권,3120238,방이역,3675,2614,1061,0,446,...,537,698,716,418,0,201,276,246,209,129
42554,20243,D,발달상권,3120233,몽촌토성역,13996,8039,5957,4,2258,...,2335,1932,1403,1099,0,992,1253,1226,1591,895
42555,20243,A,골목상권,3111035,오금공원(오주중학교),934,653,281,0,125,...,150,174,170,86,0,52,73,63,54,39
42556,20243,A,골목상권,3111046,마천역(마천초등학교),720,402,318,0,43,...,93,120,114,62,0,30,78,109,101,0
42557,20243,A,골목상권,3110960,은광여고,886,627,259,1,152,...,135,185,184,45,0,75,72,62,40,10

In [13]:
df_sales = pd.read_csv('./서울시 상권분석서비스(추정매출-상권).csv', encoding='cp949')

In [17]:
df_sales['당월_매출_금액'].idxmin()

12755

In [27]:
cond_latest_sales = df_sales['기준_년분기_코드'] == 20252
cond_area_sales   = df_sales['상권_코드_명'] == '개포지하차도 북측'
selected_sales = df_sales[cond_latest_sales & cond_area_sales]
total_sales= selected_sales['당월_매출_금액'].sum()
print(total_sales)

0

In [21]:
selected_sales = df_sales[cond_latest_sales & cond_area_sales]
selected_sales

Empty DataFrame
Columns: [기준_년분기_코드, 상권_구분_코드, 상권_구분_코드_명, 상권_코드, 상권_코드_명, 서비스_업종_코드, 서비스_업종_코드_명, 당월_매출_금액, 당월_매출_건수, 주중_매출_금액, 주말_매출_금액, 월요일_매출_금액, 화요일_매출_금액, 수요일_매출_금액, 목요일_매출_금액, 금요일_매출_금액, 토요일_매출_금액, 일요일_매출_금액, 시간대_00~06_매출_금액, 시간대_06~11_매출_금액, 시간대_11~14_매출_금액, 시간대_14~17_매출_금액, 시간대_17~21_매출_금액, 시간대_21~24_매출_금액, 남성_매출_금액, 여성_매출_금액, 연령대_10_매출_금액, 연령대_20_매출_금액, 연령대_30_매출_금액, 연령대_40_매출_금액, 연령대_50_매출_금액, 연령대_60_이상_매출_금액, 주중_매출_건수, 주말_매출_건수, 월요일_매출_건수, 화요일_매출_건수, 수요일_매출_건수, 목요일_매출_건수, 금요일_매출_건수, 토요일_매출_건수, 일요일_매출_건수, 시간대_건수~06_매출_건수, 시간대_건수~11_매출_건수, 시간대_건수~14_매출_건수, 시간대_건수~17_매출_건수, 시간대_건수~21_매출_건수, 시간대_건수~24_매출_건수, 남성_매출_건수, 여성_매출_건수, 연령대_10_매출_건수, 연령대_20_매출_건수, 연령대_30_매출_건수, 연령대_40_매출_건수, 연령대_50_매출_건수, 연령대_60_이상_매출_건수]
Index: []

[0 rows x 55 columns]

In [26]:
df_sales['기준_년분기_코드'].max()

np.int64(20252)